tap "laishulu/homebrew"

brew "defaultbrowser"
brew "direnv"
brew "fzf"
brew "gh"
brew "laishulu/homebrew/macism"  # IME切り替え（Neovim用）
brew "mise"
brew "neovim"
brew "starship"
brew "trash"       # rm の代わりに使用（復元可能）
brew "tree"
brew "zsh-autosuggestions"

cask "karabiner-elements"
cask "1password"
cask "1password-cli"
cask "alt-tab"
cask "aqua-voice"
cask "arc"
cask "chatwork"
cask "cleanshot"
cask "discord"
cask "displaylink"
cask "font-hackgen"
cask "font-noto-sans-cjk-jp"
cask "ghostty"
cask "google-chrome"
cask "homerow"
cask "logi-options+"
cask "nani"
cask "notion"
cask "obsidian"
cask "positron"
cask "raindropio"
cask "raycast"
cask "slack"
