tap "laishulu/homebrew"

brew "fzf"
brew "laishulu/homebrew/macism"  # IME切り替え（Neovim用）
brew "mise"
brew "neovim"
brew "starship"
brew "trash"       # rm の代わりに使用（復元可能）
brew "zellij"
brew "zsh-autosuggestions"

cask "1password"
cask "aqua-voice"
cask "arc"
cask "chatwork"
cask "cleanshot"
cask "discord"
cask "displaylink"
cask "font-hackgen"
cask "ghostty"
cask "google-chrome"
cask "nani"
cask "notion"
cask "obsidian"
cask "positron"
cask "raycast"
cask "slack"
cask "tailscale-app"
